version: "3"

tasks:
  lint:
    cmds:
      - go run github.com/alecthomas/go-check-sumtype/cmd/go-check-sumtype@latest -default-signifies-exhaustive=false -include-shared-interfaces ./...
      - golangci-lint run --fix .
      - golines --no-reformat-tags -w .
      - golangci-lint run
  gen:
    cmds:
      - go generate ./...
  test:
    cmds:
      - go test ./...
  test-no-cache:
    cmds:
      - go test -v -count=1 ./...
  copy:
    cmds:
      - yek ./**/*.go --ignore-patterns "*_mock*" --ignore-patterns "*_test.go" | pbcopy
