vars: {
  colors: {
    context: "transparent"
    event: "#f77730"
    cmd: "skyblue"
    actor: "yellow"
    read: "palegreen"
    pain: "#DFB0F9"
    policy: "mediumpurple"
    external: "#ff70ff"
    aggregate: "#FED49A"
  }
  common-styles: {
    text-transform: none
    stroke-width: 0
  }
  common-styles-conn: {
    font-color: "black"
  }
  rounded: {
    border-radius: 14
  }
}

classes: {
  context: {
    style: {
      fill: ${colors.context}
      stroke-dash: 6
      double-border: false
      stroke: lightgray
      ...${common-styles}
    }
  }
  context-conn: {
    style: {
      fill: "black"
      ...${common-styles}
      font-color: white
      stroke-width: 6
    }
  }
  event: {
    style: {
      fill: ${colors.event}
      ...${common-styles}
    }
  }
  event-conn: {
    style: {
      fill: ${colors.event}
      ...${common-styles}
      ...${common-styles-conn}
    }
  }
  cmd: {
    style: {
      fill: ${colors.cmd}
      ...${common-styles}
    }
  }
  cmd-conn: {
    style: {
      fill: ${colors.cmd}
      ...${common-styles}
      ...${common-styles-conn}
    }
  }
  actor: {
    style: {
      fill: ${colors.actor}
      ...${common-styles}
    }
  }
  actor-conn: {
    style: {
      fill: ${colors.actor}
      ...${common-styles}
      ...${common-styles-conn}
    }
  }
  read: {
    style: {
      fill: ${colors.read}
      ...${common-styles}
    }
  }
  read-conn: {
    style: {
      fill: ${colors.read}
      ...${common-styles}
      ...${common-styles-conn}
    }
  }
  pain: {
    style: {
      fill: ${colors.pain}
      ...${common-styles}
    }
  }
  pain-conn: {
    style: {
      fill: ${colors.pain}
      ...${common-styles}
      ...${common-styles-conn}
      stroke-dash: 3
      stroke: "black"
    }
  }
  policy: {
    style: {
      fill: ${colors.policy}
      ...${common-styles}
    }
  }
  policy-conn: {
    style: {
      fill: ${colors.policy}
      ...${common-styles}
      ...${common-styles-conn}
    }
  }
  external: {
    style: {
      fill: ${colors.external}
      ...${common-styles}
    }
  }
  external-conn: {
    style: {
      fill: ${colors.external}
      ...${common-styles}
      ...${common-styles-conn}
    }
  }
  aggregate: {
    style: {
      fill: ${colors.aggregate}
      ...${common-styles}
    }
  }
  aggregate-conn: {
    style: {
      fill: ${colors.aggregate}
      ...${common-styles}
      ...${common-styles-conn}
    }
  }
}

eventlog: {
  label: Event log

  0: {
    class: cmd
    shape: square
    style: {
      ...${rounded}
    }
  }
  1: {
    shape: square
    style: {
      ...${rounded}
      ...${common-styles}
      fill: white
    }
  }
  2: {
    class: cmd
    shape: square
    style: {
      ...${rounded}
    }
  }
  3: {
    class: aggregate
    shape: square
    style: {
      ...${rounded}
    }
  }

  4: {
    label: ...
    style: {
      fill: transparent
      stroke: transparent
      ...${rounded}
    }
  }
  5: {
    label: ...
    style: {
      fill: transparent
      stroke: transparent
      ...${rounded}
    }
  }

  100: {
    class: aggregate
    style: {
      ...${rounded}
    }
  }
  101: {
    class: aggregate
    style: {
      ...${rounded}
    }
  }
  8: {
    label: ...
    style: {
      fill: transparent
      stroke: transparent
      ...${rounded}
    }
  }
}

person/7d7e974e: {
  0: {
    shape: square
    style: {
      stroke: ${colors.cmd}
      stroke-width: 4
      stroke-dash: 2
      ...${rounded}
    }
  }
  1: {
    shape: square
    style: {
      stroke: ${colors.cmd}
      stroke-width: 4
      stroke-dash: 2
      ...${rounded}
    }
  }

  2: {
    shape: square
    style: {
      stroke: ${colors.cmd}
      stroke-width: 4
      stroke-dash: 2
      ...${rounded}
    }
  }
}

account/162accc9: {
  0: {
    shape: square
    style: {
      stroke: ${colors.event}
      stroke-width: 4
      stroke-dash: 2
      ...${rounded}
    }
  }
  1: {
    shape: square
    style: {
      stroke: ${colors.event}
      stroke-width: 4
      stroke-dash: 2
      ...${rounded}
    }
  }
  2: {
    shape: square
    style: {
      stroke: ${colors.event}
      stroke-width: 4
      stroke-dash: 2
      ...${rounded}
    }
  }
}

person/7d7e974e.0 -> eventlog.0: {
  style: {
    stroke: ${colors.cmd}
  }
}
person/7d7e974e.1 -> eventlog.2: {
  style: {
    stroke: ${colors.cmd}
  }
}
person/7d7e974e.2 -> eventlog.5: {
  style: {
    stroke: ${colors.cmd}
  }
}

account/162accc9.0 -> eventlog.3: {
  style: {
    stroke: ${colors.event}
  }
}
account/162accc9.1 -> eventlog.100: {
  style: {
    stroke: ${colors.event}
  }
}
account/162accc9.2 -> eventlog.101: {
  style: {
    stroke: ${colors.event}
  }
}
