name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        with:
          enable-cache: 'true'
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Run tests
        run: devbox run -- task test